name: coverage badge js
description: Generate coverage badge using Istanbul's JSONON  summary
author: tj-actions
inputs:
  path:
    description: 'Path to the application'
    required: true
    default: "."
  output_path:
    description: 'Writes the coverage badge to the given path'
    required: true
    default: "./coverage/badge.svg"
  report_path:
    description: 'Path to a coverage report file'
    required: true
    default: "./coverage/coverage-summary.json"

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: list
  color: white
