name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.5

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
        working-directory: test-app

      - name: Run test
        run:  yarn test -- --coverage
        working-directory: test-app

      - name: Run coverage badge js
        uses: ./
        with:
          path: test-app
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v5.3
        with:
          files: |
            test-app/coverage/badge.svg

      - name: Coverage badge has changed
        if: steps.changed-files.outputs.all_changed == 'true'
        run: |
          echo "test-app/coverage/badge.svg has uncommited changes"
          exit 1

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v3
        with:
          base: "main"
          title: "Updated coverage badge"
          branch: "chore/update-coverage-badge"
          commit-message: "Updated coverage badge."
          body: "Updated coverage badge."
          token: ${{ secrets.PAT_TOKEN }}
